runtime: go116  # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "pomodoro_backend"

vpc_access_connector:
  name: projects/vocal-clone-374416/locations/europe-west9/connectors/pomodorowork

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: auto